# Generated by Django 2.2.12 on 2020-05-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20200509_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detaroles',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'nivel de habilidades', 'verbose_name_plural': 'niveles de usuario'},
        ),
    ]
