# Generated by Django 2.2.12 on 2020-05-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_auto_20200513_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosuser',
            old_name='profeuser',
            new_name='profeUser',
        ),
    ]
